### ISSUE TITLE
Promise.map is not a function 

### ISSUE THREAD

**Issue by jakangah** [Wiredcraft/loopback-n1ql-mixin#39]
run into this a couple of times when using the mixin to auto-update couchbase 

```
Feb 10 16:17:07 omni-membership[69027] INFO:  
  system: "nsq"
  message: "fetching nsqd data"
  data: {"producers":[{"remote_address":"172.29.0.4:38030","hostname":"cc575ddbfce8","broadcast_address":"localhost","tcp_port":4150,"http_port":4151,"version":"1.1.0","tombstones":[],"topics":[]}]}
{ e: TypeError: Promise.map is not a function
    at Function.Model.createIndex (/Users/justice/workspace/omni-contact/node_modules/loopback-n1ql-mixin/lib/n1ql.js:186:20)
    at <anonymous> }
Feb 10 16:17:07 omni-membership[69027] ERROR: Promise.map is not a function
  err: TypeError: Promise.map is not a function
      at Function.Model.createIndex (./node_modules/loopback-n1ql-mixin/lib/n1ql.js:186:20)
      at <anonymous>
```

**Comment by woodpig07** [comment]
The `n1ql.js` is depending on `bluebird`
https://github.com/Wiredcraft/loopback-n1ql-mixin/blob/927eef5c6c45db6b839292a8cea083be1798d58a/lib/n1ql.js#L8

but it's not listed on package.json, `yarn.lock` has it though.
https://github.com/Wiredcraft/loopback-n1ql-mixin/blob/927eef5c6c45db6b839292a8cea083be1798d58a/package.json#L57-L61

Will need a new release to fix it.

In the meantime for a quick solution, use `yarn` to install your project dependencies, or add `bluebird` to your project `package.json`

**Comment by jakangah** [comment]
@woodpig07 would like to avoid adding dependencies to my main `package.json` unless I absolutely need to, created a pr https://github.com/Wiredcraft/loopback-n1ql-mixin/pull/40

**Comment by woodpig07** [comment]
tag `v1.1.1` for release, but I don't have permission to publish it.

**Comment by CCharlieLi** [comment]
I got a error below when trying to create view from script. I noticed that you are still using `loopback-connector-couchbase5` instead of latest version of `loopback-connector-couchbasex`.
```
ERROR: promise.asCallback is not a function
  err: TypeError: promise.asCallback is not a function
      at Couchbase.autoupdate (./node_modules/loopback-connector-couchbasex/lib/couchbaseX.js:283:20)
      at Model.boot.then (./node_modules/loopback-n1ql-mixin/lib/n1ql.js:239:35)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jakangah** [comment]
> RROR: promise.asCallback is not a function
>   err: TypeError: promise.asCallback is not a function
>       at Couchbase.autoupdate (./node_modules/loopback-connector-couchbasex/lib/couchbaseX.js:283:20)
>       at Model.boot.then (./node_modules/loopback-n1ql-mixin/lib/n1ql.js:239:35)
>       at process._tickCallback (internal/process/next_tick.js:68:7)

moving this to a separate ticket https://github.com/Wiredcraft/loopback-n1ql-mixin/issues/42

**Comment by woodpig07** [comment]
resovled in #42
