### ISSUE TITLE
bluebird issue on couchbase connector dependecy

### ISSUE THREAD

**Issue by jakangah** [Wiredcraft/loopback-n1ql-mixin#42]
**Context**
seems that there is another issue related to bluebird, the couchbase connector expects to get a bluebird promise which has the helper function `asCallback`, this seems to be causing the n1ql mixin to break 

**How to reproduce**
in order to make it easy to reproduce, I have created a branch on omni contact https://github.com/Wiredcraft/omni-contact/tree/fix-oidc
- make docker-start
- the previous step causes the error 
```
promise.asCallback is not a function
  err: TypeError: promise.asCallback is not a function
      at Couchbase.autoupdate (./node_modules/loopback-connector-couchbase5/lib/couchbase5.js:267:20)
      at Model.boot.then (./node_modules/loopback-n1ql-mixin/lib/n1ql.js:239:35)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by woodpig07** [comment]
The problem is when using the `async await` to call promise function like
```
boot(app, __dirname, async (err) => {
 
  const couchbase = app.dataSources.couchbase;
  try {
    await couchbase.autoupdate();
```
It causes conflict as the n1ql mixin set the `bluebird` as the global Promise object
https://github.com/Wiredcraft/loopback-n1ql-mixin/blob/db0e773f1e6b65a64a03e19581678754c1dd8846/lib/n1ql.js#L9

We can remove this line as I don't see it's absolute necessary to change global Promise object.

**Comment by xavierchow** [comment]
Agreed, no good practice to alter the global object as a library.

**Comment by woodpig07** [comment]
I made tag `v1.1.1`, still not able to publish it.
@xavierchow can you help to publish

**Comment by xavierchow** [comment]
@woodpig07 invited you as the mentainer.

**Comment by xavierchow** [comment]
1.1.2 published.

**Comment by woodpig07** [comment]
my test with v1.1.2 looks ok, closing
