### ISSUE TITLE
Indexing strategy

### ISSUE THREAD

**Issue by CCharlieLi** [Wiredcraft/loopback-n1ql-mixin#6]
It seems we are go with N1ql now, and we are using Couchbase community edition, a few suggestions for Indexing strategy:

- GSI replica: We can "manually" create index replication as described [here](https://forums.couchbase.com/t/index-replication-on-couchbase-community-edition/17027) since there's no such a feature in community edition.
- Use N1ql mixin to create and manage views instead of a separate script.

Any comments. @pivstone @JuhaS @zbal

**Comment by pivstone** [comment]
We are good at index strategy for now. Create a new one if you have a new idea.
